-- CreateTable
CREATE TABLE "Candidatos" (
    "idCandidato" BIGSERIAL NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "nomeCandidato" TEXT,
    "cpfCandidato" TEXT,
    "rgCandidato" TEXT,
    "sexoCandidato" TEXT,
    "estadocivilCandidato" TEXT,
    "cnhCandidato" TEXT,
    "outrosexoCandidato" TEXT,
    "categoriacnhCandidato" TEXT,
    "emailCandidato" TEXT,
    "datanascimentoCandidato" DATE,
    "linkedinCandidato" TEXT,
    "facebookCandidato" TEXT,
    "instagramCandidato" TEXT,
    "telefoneCandidato" TEXT,
    "telefone2Candidato" TEXT,
    "pcdCandidato" TEXT,
    "cidareacandidato" TEXT,
    "cepCandidato" TEXT,
    "ruaCandidato" TEXT,
    "numeroCandidato" TEXT,
    "bairroCandidato" TEXT,
    "cidadeCandidato" TEXT,
    "estadoCandidato" TEXT,
    "vagainteresseCandidato" TEXT,
    "escolaridadeCandidato" TEXT,
    "conhecimentosCandidato" TEXT,
    "wordCandidato" TEXT,
    "excelCandidato" TEXT,
    "powerpointCandidato" TEXT,
    "conhecimentosinformaticaCandidato" TEXT,
    "conhecimentoinfcandidato" TEXT,
    "possuiexperienciaCandidato" TEXT,
    "empresaCandidato" TEXT,
    "local1Candidato" TEXT,
    "atividadesdesenvolvidas1Candidato" TEXT,
    "datainicioCandidato" DATE,
    "trabalha1Candidato" TEXT,
    "datafinalCandidato" DATE,
    "empresa2Candidato" TEXT,
    "local2Candidato" TEXT,
    "atividadesdesenvolvidas2Candidato" TEXT,
    "datainicio2Candidato" DATE,
    "trabalha2Candidato" TEXT,
    "datafinal2Candidato" DATE,
    "empresa3Candidato" TEXT,
    "local3Candidato" TEXT,
    "atividadesdesenvolvidas3Candidato" TEXT,
    "datainicio3Candidato" DATE,
    "trabalha3Candidato" TEXT,
    "datafinal3Candidato" DATE,
    "fotoCandidato" TEXT,
    "parentescoCandidato" TEXT,
    "graudeparentescoenomeCandidato" TEXT,
    "datacadastroCandidato" DATE,
    "situacaoCandidato" TEXT,
    "opcionalCandidato" TEXT,

    CONSTRAINT "candidatos_pkey" PRIMARY KEY ("idCandidato")
);

-- CreateTable
CREATE TABLE "usuario" (
    "id" SERIAL NOT NULL,
    "nome" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "senhahash" TEXT NOT NULL,
    "autorizado" BOOLEAN DEFAULT false,
    "fotourl" TEXT,
    "criadoem" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Usuario_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Usuario_email_key" ON "usuario"("email");
